target_domain: "egyption history"
use_case: "question_answering"
data_sources:
  - type: "pdf"
    paths: ["data_set/raw/"]
  
base_model: "mistralai/Mistral-7B-Instruct-v0.3"
output_dir: "./mistral_egypt_lora"
training_params:
  lora_rank: 64
  learning_rate: 3e-4
  batch_size: 1
  num_epochs: 3
deployment:
  api_auth_key: "ev_charging_api_key"
  port: 8000
