target_domain: "egyption history"
use_case: "question_answering"
data_sources:
  - type: "pdf"
    paths: ["data_set/raw/"]
  
base_model: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
output_dir: "./mistral_egypt_lora"
training_params:
  lora_rank: 64
  learning_rate: 3e-4
  batch_size: 1
  num_epochs: 3
deployment:
  api_auth_key: "afb5qdvw6qfwrgqfe-wegw51"
  port: 8000
